######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 8 22:19:13 2012
######################################################################

TEMPLATE = app
TARGET = salmon
LIBS += -lGLEW -lGL -lGLU
QMAKE_CXXFLAGS += -std=c++11
DESTDIR = build
OBJECTS_DIR = build/obj

# Input
HEADERS +=
SOURCES += src/main.cpp
